__title__ = "mailer"
__version__ = "0.6.2"
__description__ = "Simple mailer micro-service for static websites"
__author__ = "Romain Clement"
__author_email__ = "r.clement88@gmail.com"
__url__ = "https://github.com/rclement/mailer"
__license__ = "MIT"
